#!/bin/bash

for user in $(grep -v '^root:' /etc/passwd | grep '/bin/false' | cut -d: -f1); do
   pkill -u $user
   sudo userdel -r "$user" > /dev/null 2>&1
done

echo "Usuarios deletados com sucesso."
