#!/bin/bash

grep -v '^root:' /etc/passwd | grep '/bin/false' | cut -d: -f1 | while read -r user; do
   pkill -u $user && sudo userdel -r "$user" && echo "Usuário $user deletado."
done

echo "Todos os usuários foram deletados."